# Generated by Django 4.1.5 on 2023-01-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_api', '0002_alter_post_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='formBody',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
