# Generated by Django 4.1.4 on 2023-01-04 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0002_alter_user_password'),
        ('posts_api', '0004_alter_post_formbody_alter_post_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_api.user'),
        ),
    ]
